version: "3.8"
services:
  acme-banking-db:
    container_name: acme-banking-db
    image: 'mysql/mysql-server:latest'
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=acme
    restart: always
  acme-banking:
    container_name: acme-banking
    image: acme-banking
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      acme-banking-db:
        condition: service_healthy
    environment:
      - co.uk.bankcorp.client=better-banking
      - co.uk.bankcorp.secret=7yrbR8XpY45bcKPP
      - MYSQL_HOST=acme-banking-db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=acme
      - DATABASE_PORT=3306
      - SERVER_PORT=8080